# Generated by Django 5.1.7 on 2025-03-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='stars',
            field=models.IntegerField(default=5),
        ),
    ]
