# Generated by Django 5.1.7 on 2025-03-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_testimonials_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='stars',
            field=models.IntegerField(default=3, max_length=5),
        ),
    ]
