# Generated by Django 5.1.7 on 2025-03-21 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_testimonials_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='stars',
        ),
        migrations.AddField(
            model_name='testimonials',
            name='rating',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
